### ISSUE TITLE
Function learning experiment is broken

### ISSUE THREAD

**Issue by jhamrick** [berkeley-cocosci/Wallace#414]
The following error shows up in `server.log`:

```
>>>> 1 1 networks out of 1 available
>>>> 1 No practice networks available.Assigning participant to experiment network 1
Traceback (most recent call last):
  File "/private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/tmpTTxQhy/w0b91fed1-e073-47c6-b2fb-1ce3/custom.py", line 592, in create_node
    network=network)
  File "/private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/tmpTTxQhy/w0b91fed1-e073-47c6-b2fb-1ce3/wallace_experiment.py", line 45, in add_node_to_network
    parent = node.neighbors(connection="from")[0]
TypeError: neighbors() got an unexpected keyword argument 'connection'
```

**Comment by suchow** [comment]
Good catch, we renamed this to `direction` recently. Will fix.
