### ISSUE TITLE
installing wallace

### ISSUE THREAD

**Issue by tobiasgerstenberg** [berkeley-cocosci/Wallace#466]
i just tried to setup wallace and got the following error message upon running wallace setup (with wallace version 0.11.6): 

Creating Wallace config file at ~/.wallaceconfig...
Traceback (most recent call last):
  File "/usr/local/bin/wallace", line 11, in <module>
    sys.exit(wallace())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wallace/command_line.py", line 80, in setup
    shutil.copyfile(src, config_path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/wallace/config/.wallaceconfig'

i checked the directory and it doesn't have a /config/ subfolder (see image below) 

![image](https://cloud.githubusercontent.com/assets/1675584/17841379/cbe32226-67e5-11e6-9b7c-caa506ed461e.png)

any help on how to proceed would be much appreciated!

**Comment by suchow** [comment]
It looks like you tried installing using pip. Despite what the documentation says, we haven't got that to work yet. Can you instead use the [developer installation instructions](http://wallace.readthedocs.io/en/latest/developing_wallace_setup_guide.html) and see if you have the same issue?

**Comment by suchow** [comment]
@tobiasgerstenberg It should now be installable via pip. Any luck?

**Comment by tobiasgerstenberg** [comment]
awesome, just tried it and it worked perfectly.

looking forward to playing around with it :) 

thanks!
